EXTRACT_TEMPERATURE = 0.0
EXTRACT_MAX_TOKENS = 1024

ASSESS_TEMPERATURE = 0.0
ASSESS_MAX_TOKENS = 1024

REPLY_TEMPERATURE = 0.3
REPLY_MAX_TOKENS = 2048

ROUTE_TEMPERATURE = 0.0
ROUTE_MAX_TOKENS = 512

IMAGE_ANALYSIS_TEMPERATURE = 0.1
IMAGE_ANALYSIS_MAX_TOKENS = 1024

# v2.0: VLM 多模态大模型配置
VLM_TEMPERATURE = 0.1
VLM_MAX_TOKENS = 1024

CHROMA_COLLECTION_NAME = "sop_knowledge"
CHROMA_EMBEDDING_MODEL = "shibing624/text2vec-base-chinese"
